disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "mynewsite"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Paul McCormack"
#   email = "youremail@example.com"
  image = "img/blowfish_logo.png"
  imageQuality = 96
  headline = "I'm only human"
#   bio = "A little bit about you"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
    { github = "https://github.com/paul-mccormack/" },
    { linkedin = "https://www.linkedin.com/in/paul-mccormack-08b04a6/" },
  ]
